version: '3.8'
services:
  database:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password

  development:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    depends_on:
      - database
